spring:
  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-2025-04-14
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true
    mcp:
      client:
        stdio:
          connections:
            brave-search-client:
              command: npx
              args: ["-y", "@modelcontextprotocol/server-brave-search"]
              env:
                BRAVE_API_KEY: "${BRAVE_API_KEY}"
            openweathermap-client:
              command: java
              args: ["-jar", "/home/tetsuya/repo/spring-ai-intro/mcp_server/target/spring-ai-mcp-demo-0.0.1-SNAPSHOT.jar"]
              env:
                OPENWEATHERMAP_API_KEY: "${OPENWEATHERMAP_API_KEY}"
